name: Student Notes CI
on:
  push:
    branches:
      - main

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List project files
        run: ls -la

      - name: Success message
        run: echo "CI Pipeline is working successfully"
